name: Encode
channels:
- bioconda
- pytorch
- conda-forge
- defaults
- anaconda

dependencies:
- python=3.8
- snakemake=5.26.1
- ucsc-liftover=377
- ucsc-bigwigtobedgraph=377
- ucsc-bedgraphtobigwig=377
- ucsc-bigWigAverageOverBed=377
- ucsc-bedRemoveOverlap=377
- bedtools=2.29.2
- deeptools=3.5.0
